insert into item_a(version, id, type) values (1, 1, 0)
insert into item_a(version, id, type) values (1, 2, 1)
insert into item_a(version, id, type) values (1, 3, 2)
insert into item_a(version, id, type) values (1, 4, 0)
insert into item_a(version, id, type) values (1, 5, 1)
insert into item_a(version, id, type) values (1, 6, 2)

insert into item_b(version, id, type) values (1, 1, 0)
insert into item_b(version, id, type) values (1, 2, 1)
insert into item_b(version, id, type) values (1, 3, 2)
insert into item_b(version, id, type) values (1, 4, 0)
insert into item_b(version, id, type) values (1, 5, 1)
insert into item_b(version, id, type) values (1, 6, 2)
